package com.kungfu.backend_service.database

import org.flywaydb.core.Flyway
import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.stereotype.Service
import java.time.Instant

@Service
class DatabaseManagerService(
    private val jdbcTemplate: JdbcTemplate,
    private val flyway: Flyway,
) {
    private val identifierRegex = Regex("^[a-zA-Z_][a-zA-Z0-9_]*$")

    fun health(): DatabaseHealth {
        val databaseTime = jdbcTemplate.queryForObject("SELECT NOW()", String::class.java)
        return DatabaseHealth(
            status = "UP",
            databaseTime = databaseTime,
            checkedAt = Instant.now().toString(),
        )
    }

    fun listTables(): List<String> {
        return jdbcTemplate.queryForList(
            """
            SELECT table_name
            FROM information_schema.tables
            WHERE table_schema = 'public'
            ORDER BY table_name
            """.trimIndent(),
            String::class.java,
        )
    }

    fun listColumns(tableName: String): List<TableColumnInfo> {
        val normalizedTable = normalizeTableName(tableName)
        ensureTableExists(normalizedTable)
        val primaryKeyColumn = findPrimaryKeyColumn(normalizedTable)

        return jdbcTemplate.query(
            """
            SELECT column_name, is_nullable, data_type, is_identity, column_default
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = ?
            ORDER BY ordinal_position
            """.trimIndent(),
            { rs, _ ->
                val columnName = rs.getString("column_name")
                val isNullable = rs.getString("is_nullable") == "YES"
                val isIdentity = rs.getString("is_identity") == "YES"
                val columnDefault = rs.getString("column_default")
                val isAutoGenerated = isIdentity || (columnDefault?.startsWith("nextval(") == true)
                TableColumnInfo(
                    name = columnName,
                    dataType = rs.getString("data_type"),
                    nullable = isNullable,
                    primaryKey = columnName == primaryKeyColumn,
                    autoGenerated = isAutoGenerated,
                )
            },
            normalizedTable,
        )
    }

    fun listRows(tableName: String, limit: Int): List<Map<String, Any?>> {
        val normalizedTable = normalizeTableName(tableName)
        ensureTableExists(normalizedTable)
        val sanitizedLimit = limit.coerceIn(1, 500)
        val quotedTable = quoteIdentifier(normalizedTable)
        val primaryKeyColumn = findPrimaryKeyColumn(normalizedTable)

        val sql = if (primaryKeyColumn != null) {
            val quotedPrimaryKey = quoteIdentifier(primaryKeyColumn)
            "SELECT * FROM $quotedTable ORDER BY $quotedPrimaryKey DESC LIMIT ?"
        } else {
            "SELECT * FROM $quotedTable LIMIT ?"
        }

        return jdbcTemplate.queryForList(sql, sanitizedLimit)
    }

    fun insertRow(tableName: String, payload: Map<String, Any?>): Map<String, Any?> {
        val normalizedTable = normalizeTableName(tableName)
        ensureTableExists(normalizedTable)
        val columns = listColumns(normalizedTable)
        val allowedColumns = columns.filter { !it.autoGenerated }.map { it.name }.toSet()

        val insertData = payload
            .filterKeys { it in allowedColumns }
            .toSortedMap()

        require(insertData.isNotEmpty()) { "No hay columnas válidas para insertar." }

        val quotedTable = quoteIdentifier(normalizedTable)
        val quotedColumns = insertData.keys.joinToString(", ") { quoteIdentifier(it) }
        val placeholders = insertData.keys.joinToString(", ") { "?" }
        val values = insertData.values.toTypedArray()
        val sql = "INSERT INTO $quotedTable ($quotedColumns) VALUES ($placeholders) RETURNING *"

        return jdbcTemplate.queryForMap(sql, *values)
    }

    fun deleteRowByPrimaryKey(tableName: String, id: String): Boolean {
        val normalizedTable = normalizeTableName(tableName)
        ensureTableExists(normalizedTable)
        val primaryKeyColumn = findPrimaryKeyColumn(normalizedTable)
            ?: throw IllegalArgumentException("La tabla '$normalizedTable' no tiene llave primaria.")

        val quotedTable = quoteIdentifier(normalizedTable)
        val quotedPrimaryKey = quoteIdentifier(primaryKeyColumn)
        val deletedRows = jdbcTemplate.update(
            "DELETE FROM $quotedTable WHERE $quotedPrimaryKey::text = ?",
            id,
        )
        return deletedRows > 0
    }

    private fun normalizeTableName(tableName: String): String {
        require(identifierRegex.matches(tableName)) {
            "Nombre de tabla inválido."
        }
        return tableName
    }

    private fun ensureTableExists(tableName: String) {
        val exists = jdbcTemplate.queryForObject(
            """
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = 'public' AND table_name = ?
            )
            """.trimIndent(),
            Boolean::class.java,
            tableName,
        ) ?: false

        require(exists) { "La tabla '$tableName' no existe." }
    }

    private fun findPrimaryKeyColumn(tableName: String): String? {
        return jdbcTemplate.query(
            """
            SELECT kcu.column_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name
             AND tc.table_schema = kcu.table_schema
            WHERE tc.table_schema = 'public'
              AND tc.table_name = ?
              AND tc.constraint_type = 'PRIMARY KEY'
            ORDER BY kcu.ordinal_position
            LIMIT 1
            """.trimIndent(),
            { rs, _ -> rs.getString("column_name") },
            tableName,
        ).firstOrNull()
    }

    private fun quoteIdentifier(identifier: String): String {
        return "\"$identifier\""
    }

    fun migrate(): MigrationSummary {
        val result = flyway.migrate()
        return MigrationSummary(
            migrationsExecuted = result.migrationsExecuted,
            targetSchemaVersion = result.targetSchemaVersion,
            initialSchemaVersion = result.initialSchemaVersion,
            database = result.database,
            flywayVersion = result.flywayVersion,
        )
    }
}

data class DatabaseHealth(
    val status: String,
    val databaseTime: String?,
    val checkedAt: String,
)

data class MigrationSummary(
    val migrationsExecuted: Int,
    val targetSchemaVersion: String?,
    val initialSchemaVersion: String?,
    val database: String,
    val flywayVersion: String,
)

data class TableColumnInfo(
    val name: String,
    val dataType: String,
    val nullable: Boolean,
    val primaryKey: Boolean,
    val autoGenerated: Boolean,
)
