ALTER TABLE instructores
DROP CONSTRAINT IF EXISTS fk_instructor_alumno;

ALTER TABLE instructores
ALTER COLUMN id_instructor ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
    pg_get_serial_sequence('instructores', 'id_instructor'),
    COALESCE((SELECT MAX(id_instructor) FROM instructores), 0) + 1,
    false
);
