ALTER TABLE alumnos
ADD COLUMN IF NOT EXISTS nombre VARCHAR(100);

UPDATE alumnos a
SET nombre = CONCAT_WS(' ', p.nombre, p.apellido_paterno, p.apellido_materno)
FROM personas p
WHERE p.id_persona = a.id_alumno
  AND (a.nombre IS NULL OR a.nombre = '');

ALTER TABLE alumnos
ALTER COLUMN nombre SET NOT NULL;

ALTER TABLE administradores
ADD COLUMN IF NOT EXISTS nombre VARCHAR(100);

UPDATE administradores ad
SET nombre = CONCAT_WS(' ', p.nombre, p.apellido_paterno, p.apellido_materno)
FROM personas p
WHERE p.id_persona = ad.id_administrador
  AND (ad.nombre IS NULL OR ad.nombre = '');

ALTER TABLE administradores
ALTER COLUMN nombre SET NOT NULL;

ALTER TABLE alumnos
DROP CONSTRAINT IF EXISTS fk_alumno_persona;

ALTER TABLE administradores
DROP CONSTRAINT IF EXISTS fk_administrador_persona;

ALTER TABLE alumnos
ALTER COLUMN id_alumno ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE administradores
ALTER COLUMN id_administrador ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
    pg_get_serial_sequence('alumnos', 'id_alumno'),
    COALESCE((SELECT MAX(id_alumno) FROM alumnos), 0) + 1,
    false
);

SELECT setval(
    pg_get_serial_sequence('administradores', 'id_administrador'),
    COALESCE((SELECT MAX(id_administrador) FROM administradores), 0) + 1,
    false
);

DROP TABLE IF EXISTS usuarios;
DROP TABLE IF EXISTS personas;
